/**
<<<<<<< HEAD
*OOPSBannerApp UC1 - OOPS Banner Display Applicatin
*
*This class demonstrates a simple Java application that displays the Object
*oriented Programming System OOPS acronym to the console.
*
*@author Developer
*@version 1.0
*/
class OOPSBannerApp{
public static void main(String[] args){
System.out.println("OOPS");
}
}
=======
*OOPSBannerApp UC2 - Banner Display Application
*
*This class demonstrates the creation of a visual banner displaying the word "OOPS"
*using ASCII art composed of asterisks (*) and spaces. The banner is printed to the 
*console using individual print statements for each line, creating a decorative
*text effect.
*
*<p>The banner is generated by printing predefined string patterns line by line,
*where each line contributes to forming the letters O,O,P,and S in a stylized format.
*This extends a basic user story by adding visual presentation to a simple message output.
*</p>
*
*@author Developer
*@version 2
*/
class OOPSBannerApp{
	public static void main(String[] args){
		
        System.out.println("   ***         ***      ******       *****  ");
        System.out.println(" **   **     **   **    **    **    **      ");
        System.out.println("**     **   **     **   **     **   **       ");
        System.out.println("**     **   **     **   **    **    **        ");
        System.out.println("**     **   **     **   ******        ***     ");
        System.out.println("**     **   **     **   **              **    ");
        System.out.println("**     **   **     **   **               **   ");
        System.out.println(" **   **     **   **    **              **    ");
        System.out.println("   ***         ***      **          *****     ");

	}
}	
>>>>>>> feature/UC2-PrintOOPS
